"""
Typst Document Generator
=========================
Generates a complete Typst ``.typ`` file from the mapped document data.
Writes the file to disk so it can be compiled by the Typst compiler.

Pipeline position:
    Template Mapper → **Typst Generator** → Typst Compilation → PDF

Accepts either:
  - Pre-mapped Typst data  (from ``/map-template``)
  - Raw document AST + conference/layout  (calls mapper internally)
"""

import os
import re
import tempfile
import shutil
from typing import Optional

from api import template_mapper

# ── Paths ──
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TYPST_DIR = os.path.join(BASE_DIR, "typst")
TEMPLATES_DIR = os.path.join(TYPST_DIR, "templates")


def generate(
    document: Optional[dict] = None,
    conference: str = "ieee",
    layout: str = "single-column",
    mapped_data: Optional[dict] = None,
    formatted_references: Optional[list[dict]] = None,
    output_dir: Optional[str] = None,
) -> dict:
    """
    Generate a Typst ``.typ`` file ready for compilation.

    Parameters
    ----------
    document : dict, optional
        Raw document AST from ``/detect-sections``.
        Ignored if ``mapped_data`` is provided.
    conference : str
        Conference template: ieee, acm, neurips, springer, elsevier
    layout : str
        Layout: single-column or double-column
    mapped_data : dict, optional
        Pre-mapped Typst data model (the ``"data"`` key from ``/map-template``).
        If provided, skips the mapping step.
    formatted_references : list[dict], optional
        Pre-formatted references from ``/format-citations``.
        Overrides any references in the mapped data.
    output_dir : str, optional
        Directory to write the .typ file. Defaults to a temp directory.

    Returns
    -------
    dict
        {
          "status": "success",
          "typst_code": "...",
          "output_path": "/path/to/paper.typ",
          "output_dir": "/path/to/dir/",
          "conference": "ieee",
          "layout": "single-column"
        }
    """
    conference = conference.lower().strip()
    layout = layout.lower().strip()

    # ── Step 1: Get the Typst data model ──
    if mapped_data:
        data = mapped_data
    elif document:
        map_result = template_mapper.map_document(document, conference, layout)
        if map_result["status"] == "error":
            return map_result
        data = map_result["data"]
    else:
        return {"status": "error", "error": "Provide either 'document' or 'mapped_data'."}

    # ── Step 2: Override references if formatted ones are provided ──
    if formatted_references:
        data = {**data, "references": formatted_references}

    # ── Step 3: Validate template path ──
    try:
        template_mapper.get_template_path(conference, layout)
    except (ValueError, FileNotFoundError) as e:
        return {"status": "error", "error": str(e)}

    # ── Step 4: Generate Typst source ──
    typst_code = _build_typst_source(data, conference, layout)

    # ── Step 5: Write to disk ──
    if output_dir is None:
        output_dir = tempfile.mkdtemp(prefix="ideaoverflow_typst_")

    os.makedirs(output_dir, exist_ok=True)
    output_path = os.path.join(output_dir, "paper.typ")

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(typst_code)

    # Copy the template file into the output directory so Typst can find it
    _copy_template_tree(conference, layout, output_dir)
    # Copy any local image assets referenced by the data (so Typst can resolve them)
    _copy_referenced_assets(data, output_dir, conference)

    return {
        "status": "success",
        "typst_code": typst_code,
        "output_path": output_path,
        "output_dir": output_dir,
        "conference": conference,
        "layout": layout,
    }


def cleanup(output_dir: str) -> None:
    """Remove the temporary output directory after use."""
    if output_dir and os.path.exists(output_dir):
        shutil.rmtree(output_dir, ignore_errors=True)


# ════════════════════════════════════════════════════════════════════
#  Typst source code generation
# ════════════════════════════════════════════════════════════════════

def _escape(text: str) -> str:
    """Escape special characters for Typst string literals."""
    text = text.replace("\\", "\\\\")
    text = text.replace('"', '\\"')
    return text


def _build_typst_source(data: dict, conference: str, layout: str) -> str:
    """
    Build a complete .typ source that imports the template
    and calls ``render(data)`` with the document data inlined.
    """
    lines = []

    # ── Header ──
    lines.append(f"// Auto-generated by IdeaOverflow — {conference.upper()} {layout}")
    lines.append(f"// Template: templates/{conference}/{layout}.typ")
    lines.append("")
    lines.append(f'#import "templates/{conference}/{layout}.typ": render')
    lines.append("")

    # ── Open render call ──
    lines.append("#render((")

    # ── Title ──
    lines.append(f'  title: "{_escape(data.get("title", "Untitled"))}",')
    lines.append("")

    # ── Authors ──
    lines.append("  authors: (")
    for author in data.get("authors", []):
        name = _escape(author.get("name", ""))
        affiliation = _escape(author.get("affiliation", ""))
        lines.append(f'    (name: "{name}", affiliation: "{affiliation}"),')
    lines.append("  ),")
    lines.append("")

    # ── Abstract ──
    abstract_text = data.get("abstract", "") or ""
    if abstract_text:
        lines.append(f'  abstract: "{_escape(abstract_text)}",')
    else:
        lines.append('  abstract: "",')
    lines.append("")

    # ── Index Terms ──
    index_terms = data.get("index_terms", []) or []
    if index_terms:
        terms_str = ", ".join(f'"{_escape(t)}"' for t in index_terms)
        lines.append(f"  index-terms: ({terms_str}),")
        lines.append("")

    # ── Content ──
    lines.append("  content: (")
    for block in data.get("content", []):
        _emit_block(block, lines, indent=4)
    lines.append("  ),")
    lines.append("")

    # ── References ──
    refs = data.get("references", [])
    if refs:
        lines.append("  references: (")
        for ref in refs:
            rid = _escape(ref.get("id", ""))
            citation = _escape(ref.get("citation", ""))
            lines.append(f'    (id: "{rid}", citation: "{citation}"),')
        lines.append("  ),")
    else:
        lines.append("  references: (),")

    # ── Close render call ──
    lines.append("))")
    lines.append("")

    return "\n".join(lines)


def _emit_block(block: dict, lines: list[str], indent: int = 4) -> None:
    """Recursively emit a content block as Typst source."""
    pad = " " * indent
    btype = block.get("type", "paragraph")

    if btype in ("section", "subsection", "subsubsection"):
        title = _escape(block.get("title", ""))
        children = block.get("content", [])
        lines.append(f'{pad}(type: "{btype}", title: "{title}", content: (')
        for child in children:
            _emit_block(child, lines, indent + 2)
        lines.append(f"{pad})),")

    elif btype == "paragraph":
        text = _escape(block.get("text", ""))
        lines.append(f'{pad}(type: "paragraph", text: "{text}"),')

    elif btype == "equation":
        math = _escape(block.get("math", ""))
        lines.append(f'{pad}(type: "equation", math: "{math}"),')

    elif btype == "image":
        src = _escape(block.get("src", ""))
        line = f'{pad}(type: "image", src: "{src}"'
        if "caption" in block:
            line += f', caption: "{_escape(block["caption"])}"'
        if "width" in block:
            line += f', width: "{_escape(block["width"])}"'
        line += "),"
        lines.append(line)

    elif btype == "table":
        cols = block.get("columns", 2)
        lines.append(f'{pad}(type: "table", columns: {cols},')
        if "caption" in block:
            lines.append(f'{pad}  caption: "{_escape(block["caption"])}",')
        if "headers" in block:
            headers = ", ".join(f'"{_escape(h)}"' for h in block["headers"])
            lines.append(f"{pad}  headers: ({headers}),")
        if "data" in block:
            lines.append(f"{pad}  data: (")
            for row in block["data"]:
                cells = ", ".join(f'"{_escape(c)}"' for c in row)
                lines.append(f"{pad}    ({cells}),")
            lines.append(f"{pad}  ),")
        lines.append(f"{pad}),")


# ════════════════════════════════════════════════════════════════════
#  Template file copying
# ════════════════════════════════════════════════════════════════════

def _copy_template_tree(conference: str, layout: str, output_dir: str) -> None:
    """
    Copy the template .typ file into the output directory,
    preserving the templates/<conf>/ directory structure
    so that the ``#import`` path resolves correctly.
    """
    src_file = os.path.join(TEMPLATES_DIR, conference, f"{layout}.typ")
    dest_dir = os.path.join(output_dir, "templates", conference)
    os.makedirs(dest_dir, exist_ok=True)

    dest_file = os.path.join(dest_dir, f"{layout}.typ")
    if not os.path.exists(dest_file):
        shutil.copy2(src_file, dest_file)


def _copy_referenced_assets(data: dict, output_dir: str, conference: str) -> None:
    """
    Copy local image assets referenced in mapped_data/content into output_dir.
    This makes relative paths like "diagram.png" work during compilation.
    """
    copied: set[str] = set()
    template_asset_dir = os.path.join(output_dir, "templates", conference)
    os.makedirs(template_asset_dir, exist_ok=True)

    def walk(blocks: list[dict]) -> None:
        for b in blocks or []:
            if not isinstance(b, dict):
                continue
            if b.get("type") == "image":
                src = (b.get("src") or "").strip()
                if not src:
                    continue
                # Skip URLs/data URIs
                if re.match(r"^[a-zA-Z][a-zA-Z0-9+.-]*://", src) or src.startswith("data:"):
                    continue

                # Absolute paths can work locally; we only copy when file exists.
                candidate_paths = []
                if os.path.isabs(src):
                    candidate_paths.append(src)
                else:
                    # Prefer project typst/ assets
                    candidate_paths.append(os.path.join(TYPST_DIR, src))
                    # Also allow relative to repo root
                    candidate_paths.append(os.path.join(BASE_DIR, src))

                src_path = next((p for p in candidate_paths if os.path.isfile(p)), None)
                if not src_path:
                    continue

                dest_name = os.path.basename(src)
                if dest_name in copied:
                    continue

                try:
                    # Copy to output root (useful if assets referenced from paper.typ)
                    shutil.copy2(src_path, os.path.join(output_dir, dest_name))
                    # Also copy next to the template file, because Typst resolves paths
                    # relative to the file where image() is called (the template).
                    shutil.copy2(src_path, os.path.join(template_asset_dir, dest_name))
                    copied.add(dest_name)
                except Exception:
                    # Asset copy is best-effort; compilation will surface missing file if needed.
                    pass

            # Recurse into nested content
            child = b.get("content")
            if isinstance(child, list):
                walk(child)

    content = data.get("content")
    if isinstance(content, list):
        walk(content)
